### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/flex-layout'

### ISSUE THREAD

**Issue by ipehimanshu** [angular-material-extensions/fab-menu#19]
I see this type error

Module not found: Error: Can't resolve '@angular/flex-layout'

So how to solve that error with ionic 5 

Thanks

**Comment by tanmayparmar** [comment]
I guess npm install @angular/flex-layout will work. However, it should be good to have that in the documentation.

**Comment by AnthonyNahas** [comment]
@HuiiBuh and @tanmayparmar thanks for answering this questions
