### ISSUE TITLE
Why mt-fab-menu tag shows empty

### ISSUE THREAD

**Issue by ipehimanshu** [angular-material-extensions/fab-menu#20]
Hello

![image](https://user-images.githubusercontent.com/26652038/126865892-5ac3a07d-bb25-4c1a-af04-9ca411059185.png)
![image](https://user-images.githubusercontent.com/26652038/126865899-92f4f8c5-771b-45dc-b78d-80cd179b6393.png)
![image](https://user-images.githubusercontent.com/26652038/126865929-f5aadbfc-b107-426c-859b-67922905b18f.png)

i am using ionic 5

Thanks

**Comment by AnthonyNahas** [comment]
please use the latest version 5.1.0

If you are still facing the same issue please consider reopening this ticket

thank you
