### ISSUE TITLE
FAB icon appear rotated

### ISSUE THREAD

**Issue by bennymeg** [angular-material-extensions/fab-menu#35]
When you choose a different icon then `add` as a main icon after opening the menu the icon appears rotated instead of the `x` icon.

#### Solution:
After the rotate animation is finished, change the icon to the `close` icon. This will fix the issue and keep the current behavior.

**Comment by AnthonyNahas** [comment]
I will appreciate a PR from you 🍻

**Comment by AnthonyNahas** [comment]
please consider reopening this issue if you are still facing the same issue
