### ISSUE TITLE
No possibility to define the menu as "mat-mini-fab"

### ISSUE THREAD

**Issue by kevinclerc** [angular-material-extensions/fab-menu#6]
It would be greate, if you can define the size of the buttons.

In Angular you can define "mat-fab" buttons  and also "mat-mini-fab"
An @Input to define which you would like to use, would be great.

**Comment by AnthonyNahas** [comment]
I will put that on my roadmap for the next release! 

🍻

**Comment by kevinclerc** [comment]
Do you have a plan, when the next release will be released?

**Comment by kevinclerc** [comment]
still no plan to implement this feature?

**Comment by AnthonyNahas** [comment]
```html
<mat-fab-menu color="primary" 
              [fabButtons]="fabButtonsRandom">
</mat-fab-menu>

<!-- or if you prefer the mini version -->

<mat-mini-fab-menu color="primary"
              [fabButtons]="fabButtonsRandom">
</mat-mini-fab-menu>
```

this will go live in v6.1.0 in few minutes

**Comment by AnthonyNahas** [comment]
v6.1.0 is now live

you can use now the mini version with `mat-mini-fab-menu`

cheers
